<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE bookstore [
<!ELEMENT bookstore (book)+>
<!ELEMENT book (title,author,year,price)>
<!ATTLIST book
  category NMTOKEN #REQUIRED
  tag NMTOKEN #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  lang NMTOKEN #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<bookstore> 
  <book category="COOKING" tag="first">
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>30.00</price>
  </book>
  <book category="CHILDREN">
    <title lang="en">Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
  </book>
</bookstore>